-- 1. Find the total revenue generated by each product category.--
select b.category,sum(a.quantity*b.price)as total_revenue from order_items a join products b 
on a.product_id=b.product_id
group by b.category;
-- 2. Identify the customer who has generated the highest total revenue.--
select a.customer_name,sum(b.quantity*c.price) as Total_revenue
from customers a join orders d on a.customer_id=d.customer_id
join order_items b join products c on b.product_id=c.product_id
group by a.customer_name
order by Total_revenue desc 
limit 1;
-- 3. Retrieve the top 3 most sold products based on quantity.--
select a.product_name,sum(b.quantity) as top_3_quantity from products a join order_items b 
on a.product_id=b.product_id
group by a.product_name
order by top_3_quantity desc 
limit 3;
-- 4. Find the total number of orders placed by each customer. --
select a.customer_name,count(b.order_id) as total_orders
from customers a left join orders b on a.customer_id=b.customer_id
group by a.customer_name;
-- 5. Identify customers who have never placed an order.--
select a.customer_name ,b.order_id as total_orders from 
customers a left join orders b on a.customer_id=b.customer_id
where b.order_id is null;
-- 6. Find the order that generated the highest revenue. --
select a.order_id,sum(a.quantity*b.price) as Total_revenue from 
order_items a join products b on a.product_id=b.product_id
group by a.order_id
order by total_revenue desc
limit 1;
-- 7. Calculate cumulative revenue by order date. --
select a.order_date,sum(b.quantity*c.price)as total_revenue,sum(sum(b.quantity*c.price)) over( order by a.order_date)
as cumulative_revenue from orders a join order_items b on a.order_id=b.order_id
join products c on b.product_id=c.product_id
group by a.order_date
-- 8. Identify the most expensive product in each category.
select * from(select * ,rank() over(partition by category order by price desc) as rn from products)  t
where rn=1
-- 9.Find the latest order placed by each customer.
select * from(select a.customer_name,b.customer_id,b.order_date,row_number() 
over(partition by b.customer_id order by b.order_date desc)
as rn from customers a join orders b on a.customer_id=b.customer_id) t
where rn=1; 
